server:
  port: 9004

spring:
  application:
    name: EMAIL-SERVICE
  mail:
    host: smtp.gmail.com
    port: 587
    username: devemailservice302@gmail.com
    password: 
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
