server:
  port: 8080
spring:
  application:
    name: employee
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/employee
    username: employee_management_admin
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
        show-sql: 'true'